version: '3.9'

services:
  postgres:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=boilerplate
    ports:
      - 5432:5432
    networks:
      - boilerplate-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.9
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    networks:
      - boilerplate-network

  backend:
    container_name: backend
    restart: unless-stopped
    image: backend:1.0.0
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    ports:
      - 5000:5000
    networks:
      - boilerplate-network
    depends_on:
      - postgres
      - redis

  frontend:
    container_name: frontend
    restart: unless-stopped
    image: frontend:1.0.0
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    networks:
      - boilerplate-network
    ports:
      - 3000:3000
    depends_on:
      - backend

networks:
  boilerplate-network:
    driver: bridge
