version: "3.9"
services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - boilerplate-network
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.0.9
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./backend/redis-data:/data
    networks:
      - boilerplate-network
  server:
    container_name: backend
    restart: unless-stopped
    image: backend:1.0.0
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "5000:5000"
    networks:
      - boilerplate-network
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/usr/src/server
      - /usr/src/server/node_modules
  frontend:
    container_name: frontend
    restart: unless-stopped
    image: frontend:1.0.0
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    networks:
      - boilerplate-network
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    environment:
      - CHOKDIR_USERPOOLING=true
networks:
  boilerplate-network:
    driver: bridge
