version: "3.9"
services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - boilerplate-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.0.9
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - boilerplate-network
  backend:
    container_name: backend
    restart: unless-stopped
    image: backend:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5000:5000"
    networks:
      - boilerplate-network
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/backend
      - /usr/src/backend/node_modules
networks:
  boilerplate-network:
    driver: bridge
